version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml
          
    build_docker_image:
      docker:
        - image: circleci/node:12
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - run:
            name: Build Docker image
            command: |
              export TAG=0.2.<< pipeline.number >>
              export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME            
              docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
              echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
              docker push $DOCKER_LOGIN/$IMAGE_NAME
workflows:
  build-and-test:
    jobs:
      - test-python
      - build_docker_image:
          requires:
            - build