apiVersion: v1
kind: Service
metadata:
  name: buypotato-backend
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: backend.staging.wadestern.com
spec:
  selector:
    app: buypotato-backend
  ports:
  - protocol: "TCP"
    port: 7200
    targetPort: 7200
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buypotato-backend
spec:
  selector:
    matchLabels:
      app: buypotato-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: buypotato-backend
    spec:
      containers:
      - name: buypotato-backend
        image: dudesm00thie/tastybackend
        imagePullPolicy: Always
        ports:
        - containerPort: 7200
        env:
        - name: FRONTEND_HOST
          value: frontend.staging.mstern.com
